# Generated by Django 3.2.5 on 2022-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='prices',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
