# Generated by Django 3.2.5 on 2022-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlistings_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='prices',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
