# Generated by Django 3.2.5 on 2022-04-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_bid_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
