# Generated by Django 3.2.5 on 2022-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_bid_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_author',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='bid_author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
