# Generated by Django 3.2.5 on 2022-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctionlistings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
