# Generated by Django 3.2.5 on 2022-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='close_bid',
            field=models.BooleanField(default=False),
        ),
    ]
